spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fleet_manager?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true